// web/src/components/NavSidebar.vue
<script setup lang="ts">
import { useRoute, useRouter } from 'vue-router'

const route = useRoute()
const router = useRouter()

const navItems = [
  { name: 'overview', label: '总览' },
  { name: 'memory', label: '记忆' },
  { name: 'chat', label: '对话' },
  { name: 'brain', label: '大脑' },
  { name: 'gate', label: 'Gate' },
  { name: 'stream', label: '流' },
  { name: 'stats', label: '用量' },
  { name: 'logs', label: '日志' },
  { name: 'settings', label: '设置' },
]

function openInBrowser() {
  if ((window as any).pywebview?.api) {
    ;(window as any).pywebview.api.open_in_browser()
  } else {
    window.open(window.location.href, '_blank')
  }
}
</script>

<template>
  <nav class="nav-sidebar">
    <div class="nav-logo" @click="openInBrowser" title="在浏览器中打开">M</div>
    <div class="nav-items">
      <button
        v-for="item in navItems"
        :key="item.name"
        class="nav-item"
        :class="{ active: route.name === item.name }"
        @click="router.push({ name: item.name })"
      >
        <span class="nav-label">{{ item.label }}</span>
      </button>
    </div>
  </nav>
</template>

<style scoped>
.nav-sidebar {
  width: 80px;
  background: #1a1d27;
  border-right: 1px solid #2d3149;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 16px 0;
  flex-shrink: 0;
}
.nav-logo {
  font-size: 16px; font-weight: 700; color: #a78bfa;
  margin-bottom: 24px; cursor: pointer; border-radius: 8px;
  padding: 6px 4px; transition: background .2s;
}
.nav-logo:hover { background: #7c3aed22; }
.nav-items { display: flex; flex-direction: column; gap: 6px; flex: 1; width: 100%; padding: 0 10px; }
.nav-item {
  display: flex; flex-direction: column; align-items: center; gap: 4px;
  padding: 10px 4px; border: none; border-radius: 8px;
  background: transparent; color: #64748b; font-size: 11px;
  cursor: pointer; transition: all .2s; width: 100%;
}
.nav-item:hover { background: #1e293b; color: #94a3b8; }
.nav-item.active { background: #7c3aed22; color: #a78bfa; }
.nav-label { font-weight: 600; }
</style>

// web-react/src/components/NavSidebar.tsx
import { useEffect, useState } from 'react'
import { useRouter } from '../router'
import './NavSidebar.css'

const navItems = [
  { name: 'overview', label: '总览', path: '/overview' },
  { name: 'memory', label: '记忆', path: '/memory' },
  { name: 'chat', label: '对话', path: '/chat' },
  { name: 'brain', label: '大脑', path: '/brain' },
  { name: 'gate', label: 'Gate', path: '/gate' },
  { name: 'stream', label: '流', path: '/stream' },
  { name: 'stats', label: '用量', path: '/stats' },
  { name: 'logs', label: '日志', path: '/logs' },
  { name: 'settings', label: '设置', path: '/settings' },
]

export function NavSidebar() {
  const { path, navigate } = useRouter()

  function openInBrowser() {
    const electronApi = (window as any).electronAPI
    if (electronApi?.openInBrowser) {
      electronApi.openInBrowser()
    } else if ((window as any).pywebview?.api) {
      ;(window as any).pywebview.api.open_in_browser()
    } else {
      window.open(window.location.href, '_blank')
    }
  }

  return (
    <nav className="nav-sidebar">
      <div className="nav-logo" onClick={openInBrowser} title="在浏览器中打开">M</div>
      <div className="nav-items">
        {navItems.map((item) => (
          <button
            key={item.name}
            className={`nav-item${path.startsWith(item.path) ? ' active' : ''}`}
            onClick={() => navigate(item.path)}
          >
            <span className="nav-label">{item.label}</span>
          </button>
        ))}
      </div>
    </nav>
  )
}
