// web/src/views/ChatView/ChatView.vue
<script setup lang="ts">
import { ref, onMounted, onActivated, onDeactivated, onUnmounted, nextTick, computed } from 'vue'
import { chatViewModel } from './index'
import { useRouter } from 'vue-router'

const router = useRouter()
const inputText = ref('')
const messagesEl = ref<HTMLElement | null>(null)
const showSettings = ref(false)
const systemPersona = ref('')
const saving = ref(false)
const savedTip = ref(false)
const quotePreview = ref('')
const quoteIndex = ref(-1)
const showScrollBtn = ref(false)

const weworkConnected = ref(false)

async function loadWeworkStatus() {
  try {
    const r = await fetch('/gate/status')
    const d = await r.json()
    weworkConnected.value = d.connected
  } catch {}
}

function onScroll() {
  const el = messagesEl.value
  if (!el) return
  showScrollBtn.value = el.scrollHeight - el.scrollTop - el.clientHeight > 100
}

onMounted(async () => {
  chatViewModel.setScrollFn(scrollToBottom)
  await chatViewModel.loadMessages()
  chatViewModel.startStatePolling()
  await loadWeworkStatus()
})

// KeepAlive 切回时刷新状态和滚动到底部
onActivated(() => {
  chatViewModel.loadState()
  chatViewModel.startEventStream()
  scrollToBottom()
})

// KeepAlive 离开时停止轮询节省资源
onDeactivated(() => {
  chatViewModel.stopStatePolling()
})

onUnmounted(() => {
  chatViewModel.stopStatePolling()
})

function scrollToBottom() {
  nextTick(() => {
    if (messagesEl.value) {
      messagesEl.value.scrollTop = messagesEl.value.scrollHeight
    }
  })
}

const proactiveLoading = ref(false)

// 大脑循环详细面板折叠状态
const showBrainDetail = ref(false)
const brain = computed(() => chatViewModel.loopState.brain)

function fmtIdle(seconds: number): string {
  if (seconds < 60) return `${seconds}s`
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m`
  const h = Math.floor(seconds / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  return `${h}h${m ? ` ${m}m` : ''}`
}

function formatDriveLabel(key: string): string {
  const map: Record<string, string> = { curiosity: '好奇', companionship: '陪伴', self_expression: '表达', completion: '完成' }
  return map[key] || key
}

async function handleProactive() {
  if (proactiveLoading.value) return
  proactiveLoading.value = true
  await chatViewModel.triggerProactive()
  proactiveLoading.value = false
}

async function handleSend() {
  let text = inputText.value.trim()
  if (!text || chatViewModel.sending.value) return
  if (quotePreview.value) {
    text = `> ${quotePreview.value}\n\n${text}`
    quotePreview.value = ''
  }
  inputText.value = ''
  await chatViewModel.sendMessage(text)
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault()
    handleSend()
  }
}

function handleClear() {
  chatViewModel.clearChat()
}

async function openSettings() {
  showSettings.value = true
  savedTip.value = false
  try {
    const resp = await fetch('/settings/chat')
    const json = await resp.json()
    systemPersona.value = json.data?.system_persona || ''
  } catch {
    systemPersona.value = ''
  }
}

async function saveSettings() {
  saving.value = true
  try {
    await fetch('/settings/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ system_persona: systemPersona.value }),
    })
    savedTip.value = true
    setTimeout(() => { savedTip.value = false }, 2000)
  } catch (e) {
    console.error('save settings failed:', e)
  } finally {
    saving.value = false
  }
}

function closeSettings() {
  showSettings.value = false
}

function quoteMsg(text: string, index: number) {
  const lines = text.split('\n').filter(Boolean)
  let quote = lines.slice(0, 3).join('\n')
  if (lines.length > 3) quote += '\n...'
  quotePreview.value = quote
  quoteIndex.value = index
  nextTick(() => {
    const ta = document.querySelector('.chat-input') as HTMLTextAreaElement
    ta?.focus()
  })
}

function jumpToQuote() {
  if (quoteIndex.value < 0) return
  const el = messagesEl.value
  if (!el) return
  const msgs = el.querySelectorAll('.message')
  const target = msgs[quoteIndex.value] as HTMLElement
  if (target) {
    target.scrollIntoView({ behavior: 'smooth', block: 'center' })
    target.style.transition = 'background 0.5s'
    target.style.background = 'rgba(124, 58, 237, 0.15)'
    setTimeout(() => { target.style.background = '' }, 1500)
  }
  clearQuote()
}

function clearQuote() {
  quotePreview.value = ''
  quoteIndex.value = -1
}

async function copyMsgContent(text: string) {
  try {
    await navigator.clipboard.writeText(text)
  } catch {
    const ta = document.createElement('textarea')
    ta.value = text
    ta.style.position = 'fixed'
    ta.style.opacity = '0'
    document.body.appendChild(ta)
    ta.select()
    document.execCommand('copy')
    document.body.removeChild(ta)
  }
  // 浮动提示
  const flash = document.createElement('div')
  flash.className = 'copy-flash'
  flash.textContent = '已复制'
  document.body.appendChild(flash)
  setTimeout(() => flash.remove(), 1200)
}

/* 简单 markdown 渲染 */
function renderContent(msg: { role: string; content: string }) {
  if (msg.role === 'user') return escapeHtml(msg.content)
  // assistant: 简单 markdown（粗体、代码、换行）
  let html = escapeHtml(msg.content)
  // 代码块
  html = html.replace(/```(\w*)\n([\s\S]*?)```/g, '<pre><code class="lang-$1">$2</code></pre>')
  // 行内代码
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>')
  // 粗体
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
  // 斜体
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>')
  // 换行
  html = html.replace(/\n/g, '<br>')
  return html
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

/* 意识状态条 */
const stateLabel = computed(() => {
  const s = chatViewModel.loopState
  if (s.is_busy) return { icon: '🟡', text: '思考中...', cls: 'busy' }
  if (s.idle_enabled) {
    const count = s.idle_count
    return { icon: '🟢', text: `已思考 ${count} 次`, cls: 'idle' }
  }
  return { icon: '⚪', text: '意识流已暂停', cls: 'paused' }
})

/* Token 用量 */
const tokenPercent = computed(() => {
  const max = chatViewModel.loopState.max_context_tokens || 400000
  const used = chatViewModel.loopState.prompt_tokens || 0
  return Math.min((used / max) * 100, 100)
})

const tokenColor = computed(() => {
  const p = tokenPercent.value / 100
  // HSL 插值：0% → 绿(120°)  50% → 黄(60°)  100% → 红(0°)
  const hue = Math.round(120 - p * 120)
  return `hsl(${hue}, 80%, 45%)`
})

/* 时间格式化 */
function timeAgo(ts: number | null): string {
  if (!ts) return ''
  const diff = Math.floor((Date.now() / 1000) - ts)
  if (diff < 60) return `${diff}秒前`
  if (diff < 3600) return `${Math.floor(diff / 60)}分钟前`
  return `${Math.floor(diff / 3600)}小时前`
}

/* 渲染时间分隔线：日期变化时显示 */
function getDateSeparator(currentTime: string, prevTime: string | null): string {
  if (!currentTime) return ''
  const curDate = currentTime.slice(0, 10) // "2026-06-08"
  if (!prevTime) return curDate // 第一条
  const prevDate = prevTime.slice(0, 10)
  if (curDate !== prevDate) return curDate
  return ''
}

/* 格式化消息时间：显示 HH:mm:ss */
function formatMsgTime(time: string): string {
  if (!time) return ''
  const m = time.match(/\d{2}:\d{2}:\d{2}/)
  return m ? m[0] : ''
}
</script>

<template>
  <div class="chat-wrap">
    <!-- 顶部状态条 -->
    <div class="status-bar" :class="stateLabel.cls">
      <span class="status-icon">{{ stateLabel.icon }}</span>
      <span class="status-text">{{ stateLabel.text }}</span>
      <template v-if="chatViewModel.loopState.idle_enabled && chatViewModel.loopState.last_thought_at">
        <span class="status-detail">上次 {{ timeAgo(chatViewModel.loopState.last_thought_at) }}</span>
      </template>

      <button class="status-btn" @click="openSettings" title="系统提示词">⚙</button>
      <button class="status-btn" @click="handleClear" title="清空对话">🗑</button>
    </div>

    <!-- 大脑循环状态条（简略信息 + 展开按钮） -->
    <div v-if="brain" class="brain-bar" :class="{ running: brain.scheduler_running }" @click="showBrainDetail = !showBrainDetail">
      <span class="brain-bar-icon">{{ brain.scheduler_running ? '🧠' : '💤' }}</span>
      <span class="brain-bar-activity">{{ brain.current_activity || 'wait' }}{{ brain.current_focus ? ': ' + brain.current_focus.slice(0, 20) : '' }}</span>
      <span class="brain-bar-idle">{{ fmtIdle(brain.idle_seconds || 0) }}</span>
      <span v-if="brain.pending_expression_count > 0" class="brain-bar-pending">{{ brain.pending_expression_count }} 待表达</span>
      <span class="brain-bar-toggle">{{ showBrainDetail ? '▲' : '▼' }}</span>
    </div>

    <!-- 大脑循环详细面板（折叠） -->
    <div v-if="showBrainDetail && brain" class="brain-detail">
      <div class="bd-section">
        <div class="bd-title">🧬 驱动力</div>
        <div class="bd-drives">
          <div v-for="(val, key) in brain.drives" :key="key" class="bd-drive">
            <span class="bd-drive-label">{{ formatDriveLabel(key) }}</span>
            <div class="bd-drive-bar"><div class="bd-drive-fill" :style="{ width: (val * 100) + '%' }"></div></div>
            <span class="bd-drive-val">{{ (val * 100).toFixed(0) }}%</span>
          </div>
        </div>
      </div>

      <div v-if="brain.top_concerns?.length" class="bd-section">
        <div class="bd-title">🎯 当前关注</div>
        <div class="bd-concerns">
          <span v-for="c in brain.top_concerns" :key="c.node_id" class="bd-concern" :title="'effective: ' + c.effective">{{ c.node_id }}</span>
        </div>
      </div>

      <div class="bd-section bd-meta">
        <span class="bd-meta-item">能量 {{ (brain.energy * 100).toFixed(0) }}%</span>
        <span class="bd-meta-item">心情 {{ brain.mood?.label || brain.mood?.valence?.toFixed(2) || '--' }}</span>
        <span class="bd-meta-item">{{ brain.open_loop_count || 0 }} 闭环</span>
      </div>

      <div v-if="brain.reflection?.beliefs?.length || brain.reflection?.interests?.length" class="bd-section">
        <div class="bd-title">💭 反思</div>
        <div class="bd-reflection">
          <div v-if="brain.reflection.beliefs?.length" class="bd-rf-row">
            <span class="bd-rf-label">信念</span>
            <span class="bd-rf-text">{{ brain.reflection.beliefs.join('; ') }}</span>
          </div>
          <div v-if="brain.reflection.interests?.length" class="bd-rf-row">
            <span class="bd-rf-label">兴趣</span>
            <span class="bd-rf-text">{{ brain.reflection.interests.join('; ') }}</span>
          </div>
          <div v-if="brain.reflection.last_reflection_at" class="bd-rf-row dim">
            <span class="bd-rf-label">反思于</span>
            <span class="bd-rf-text">{{ brain.reflection.last_reflection_at.slice(0, 19) }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- 消息列表 -->
    <div class="messages" ref="messagesEl" @scroll="onScroll">
      <div v-if="!chatViewModel.messages.length" class="empty-hint">
        <div class="empty-icon">💭</div>
        <div>开始与 AiBrain 对话</div>
        <div class="empty-sub">AI 会自动检索记忆库来理解上下文</div>
      </div>

      <template v-for="(msg, i) in chatViewModel.messages" :key="i">
        <!-- 日期分隔线 -->
        <div v-if="getDateSeparator(msg.created_at || '', (chatViewModel.messages[i-1]?.created_at || null))" class="date-separator">
          {{ getDateSeparator(msg.created_at || '', (chatViewModel.messages[i-1]?.created_at || null)) }}
        </div>
        <div
          class="message"
          :class="[
            msg.role,
            { thought: msg.is_thought === 1 },
          ]"
        >
          <!-- 思绪标记 -->
          <span v-if="msg.is_thought === 1" class="thought-badge">💭 思绪</span>
          <!-- 消息内容 -->
          <div class="msg-content" v-html="renderContent(msg)"></div>
          <!-- 流式状态 + 光标（仅流式期间显示） -->
          <div v-if="msg.isStreaming" class="stream-status">
            <span class="stream-label">{{ chatViewModel.currentStatus.value }}</span>
            <span class="cursor">▌</span>
          </div>
          <!-- 时间戳 + 耗时 -->
          <div v-if="msg.created_at" class="msg-footer" :class="msg.role">
            <span class="msg-time">{{ formatMsgTime(msg.created_at) }}</span>
          </div>
        </div>
        <!-- 气泡操作栏 -->
        <div class="msg-actions" :class="msg.role" v-if="!msg.isStreaming">
          <button class="action-btn" @click="copyMsgContent(msg.content)" title="复制">📋</button>
          <button class="action-btn" @click="quoteMsg(msg.content, i)" title="引用">💬</button>
        </div>
      </template>
      <!-- 滚动到底部按钮 -->
      <button v-if="showScrollBtn" class="scroll-bottom-btn" @click="scrollToBottom">⬇</button>
    </div>

    <!-- 引用预览 -->
    <div v-if="quotePreview" class="quote-preview">
      <div class="quote-preview-bar"></div>
      <div class="quote-preview-text">{{ quotePreview }}</div>
      <button class="quote-preview-close" @click="clearQuote">✕</button>
    </div>
    <!-- 输入区 -->
    <div class="input-area">
      <textarea
        v-model="inputText"
        class="chat-input"
        placeholder="输入消息... (Enter 发送, Shift+Enter 换行)"
        rows="1"
        @keydown="handleKeydown"
        :disabled="chatViewModel.sending.value"
      ></textarea>
      <button
        class="send-btn"
        @click="handleSend"
        :disabled="chatViewModel.sending.value || !inputText.trim()"
        title="发送"
      >➤</button>
      <button
        class="proactive-btn"
        @click="handleProactive"
        :disabled="proactiveLoading"
        title="猫猫主动说一句"
      >💬</button>
    </div>

    <!-- Token 用量 -->
    <div class="token-bar">
      <div class="token-bar-track">
        <div class="token-bar-fill" :style="{ width: tokenPercent + '%', background: tokenColor }"></div>
      </div>
      <span class="token-label">{{ (chatViewModel.loopState.prompt_tokens / 1000).toFixed(1) || 0 }}k / {{ (chatViewModel.loopState.max_context_tokens / 1000).toFixed(1) || '400' }}k ({{ tokenPercent.toFixed(1) }}%)</span>
    </div>

    <!-- 系统提示词设置弹窗 -->
    <Teleport to="body">
      <div v-if="showSettings" class="modal-overlay" @click.self="closeSettings">
        <div class="modal-panel">
          <div class="modal-header">
            <div class="modal-title">系统提示词</div>
            <button class="modal-close" @click="closeSettings">✕</button>
          </div>
          <div class="modal-body">
            <textarea
              v-model="systemPersona"
              class="modal-textarea"
              placeholder="输入系统提示词..."
              rows="8"
            ></textarea>
          </div>
          <div class="modal-footer">
            <span v-if="savedTip.value" class="save-tip">✓ 已保存</span>
            <button class="btn-cancel" @click="closeSettings">取消</button>
            <button class="btn-save" @click="saveSettings" :disabled="saving.value">
              {{ saving.value ? '保存中...' : '保存' }}
            </button>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>

<style scoped>
.chat-wrap {
  display: flex;
  flex-direction: column;
  height: 100%;
  box-sizing: border-box;
  flex: 1;
}

/* ── 状态条 ── */
.status-bar {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 16px;
  background: #1a1d27;
  border-bottom: 1px solid #2d3149;
  font-size: 12px;
  color: #94a3b8;
  flex-shrink: 0;
}
.status-bar.busy { color: #fbbf24; }
.status-bar.idle { color: #86efac; }
.status-bar.paused { color: #64748b; }
.status-icon { font-size: 10px; }
.status-text { font-weight: 600; }
.status-detail { margin-left: auto; font-size: 11px; color: #64748b; }
.status-btn {
  background: none; border: none; color: #64748b; font-size: 14px;
  cursor: pointer; padding: 2px 4px; border-radius: 4px; transition: all .15s;
}
.status-btn:hover { color: #a78bfa; background: #2d3149; }

/* ── 消息列表 ── */
.messages {
  flex: 1;
  overflow-y: auto;
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 10px;
  position: relative;
}

.empty-hint {
  text-align: center;
  color: #475569;
  padding: 60px 20px;
  font-size: 14px;
}
.empty-icon { font-size: 40px; margin-bottom: 12px; }
.empty-sub { font-size: 12px; color: #334155; margin-top: 6px; }

/* ── 消息气泡 ── */
.message {
  max-width: 80%;
  padding: 10px 14px;
  border-radius: 12px;
  font-size: 13px;
  line-height: 1.6;
  word-break: break-word;
  position: relative;
  user-select: text;
}

.message.user {
  align-self: flex-end;
  background: #7c3aed;
  color: #fff;
  border-bottom-right-radius: 4px;
}

.message.assistant {
  align-self: flex-start;
  background: #1e293b;
  color: #e2e8f0;
  border-bottom-left-radius: 4px;
}

.message.thought {
  background: rgba(139, 92, 246, 0.12);
  border-left: 3px solid #7c3aed;
  font-style: italic;
  color: #c4b5fd;
  max-width: 70%;
}

.thought-badge {
  display: inline-block;
  font-size: 10px;
  font-style: normal;
  color: #a78bfa;
  margin-bottom: 4px;
  opacity: 0.7;
}

/* 时间戳底部栏 */
.msg-footer {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 4px;
}
.msg-footer.assistant {
  justify-content: flex-start;
}
.msg-footer.user {
  justify-content: flex-end;
}
.msg-time {
  font-size: 11px;
  color: #e2e8f0;
}

/* 日期分隔线 */
.date-separator {
  text-align: center;
  font-size: 11px;
  color: #475569;
  padding: 8px 0;
  position: relative;
}
.date-separator::before,
.date-separator::after {
  content: '';
  position: absolute;
  top: 50%;
  width: 30%;
  height: 1px;
  background: #2d3149;
}
.date-separator::before { left: 0; }
.date-separator::after { right: 0; }

.msg-content {
  user-select: text;
  -webkit-user-select: text;
}
.msg-content :deep(pre) {
  background: #0f1117;
  border: 1px solid #2d3149;
  border-radius: 6px;
  padding: 8px 10px;
  overflow-x: auto;
  margin: 6px 0;
  font-size: 12px;
}
.msg-content :deep(code) {
  background: #0f1117;
  padding: 1px 4px;
  border-radius: 3px;
  font-size: 12px;
  font-family: 'Cascadia Code', 'Fira Code', monospace;
}
.msg-content :deep(pre code) {
  background: none;
  padding: 0;
}

/* 流式状态 + 光标（仅流式期间显示） */
.stream-status {
  display: flex;
  align-items: center;
  gap: 4px;
  margin-top: 2px;
}
.stream-label {
  font-size: 10px;
  color: #a78bfa;
  opacity: 0.7;
}
.cursor {
  display: inline-block;
  animation: blink 0.8s infinite;
  color: #a78bfa;
  font-weight: bold;
}
@keyframes blink {
  0%, 100% { opacity: 1; }
  50% { opacity: 0; }
}

/* ── 引用预览 ── */
.quote-preview {
  display: flex;
  align-items: flex-start;
  gap: 8px;
  padding: 8px 16px;
  background: #1a1d27;
  border-top: 1px solid #2d3149;
  border-bottom: 1px solid #2d3149;
  flex-shrink: 0;
}
.quote-preview-bar {
  width: 3px;
  flex-shrink: 0;
  align-self: stretch;
  background: #7c3aed;
  border-radius: 2px;
}
.quote-preview-text {
  flex: 1;
  font-size: 12px;
  color: #94a3b8;
  line-height: 1.5;
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  white-space: pre-wrap;
  word-break: break-all;
}
.quote-preview-close {
  background: none;
  border: none;
  color: #64748b;
  font-size: 14px;
  cursor: pointer;
  padding: 2px 4px;
  border-radius: 4px;
  flex-shrink: 0;
}
.quote-preview-close:hover {
  color: #e2e8f0;
  background: #2d3149;
}

/* ── Token 用量 ── */
.token-bar {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 4px 16px;
  background: #0f1117;
  border-top: 1px solid #1a1d27;
  flex-shrink: 0;
}
.token-bar-track {
  flex: 1;
  height: 4px;
  background: #1e293b;
  border-radius: 2px;
  overflow: hidden;
}
.token-bar-fill {
  height: 100%;
  border-radius: 2px;
  transition: width 0.5s ease, background 0.5s ease;
}
.token-label {
  font-size: 10px;
  color: #e2e8f0;
  white-space: nowrap;
  min-width: 80px;
  text-align: right;
}

/* ── 输入区 ── */
.input-area {
  display: flex;
  align-items: flex-end;
  gap: 8px;
  padding: 12px 16px;
  background: #1a1d27;
  border-top: 1px solid #2d3149;
  flex-shrink: 0;
}

.chat-input {
  flex: 1;
  background: #0f1117;
  border: 1px solid #2d3149;
  border-radius: 8px;
  color: #e2e8f0;
  padding: 10px 12px;
  font-size: 13px;
  font-family: inherit;
  resize: none;
  outline: none;
  min-height: 40px;
  max-height: 120px;
  line-height: 1.5;
}
.chat-input:focus { border-color: #7c3aed; }
.chat-input:disabled { opacity: 0.5; }
.chat-input::placeholder { color: #475569; }

.send-btn {
  width: 40px;
  height: 40px;
  border: none;
  border-radius: 8px;
  background: #7c3aed;
  color: #fff;
  font-size: 16px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all .15s;
  flex-shrink: 0;
}
.send-btn:hover:not(:disabled) { background: #6d28d9; }
.send-btn:disabled { opacity: 0.4; cursor: not-allowed; }
.send-btn:active:not(:disabled) { transform: scale(0.95); }

.proactive-btn {
  width: 36px;
  height: 36px;
  border: 1px solid #475569;
  border-radius: 8px;
  background: transparent;
  color: #94a3b8;
  font-size: 14px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all .15s;
  flex-shrink: 0;
}
.proactive-btn:hover:not(:disabled) {
  background: #334155;
  color: #e2e8f0;
  border-color: #7c3aed;
}
.proactive-btn:disabled { opacity: 0.4; cursor: not-allowed; }

/* ── 滚动到底部按钮 ── */
.scroll-bottom-btn {
  position: absolute;
  bottom: 60px;
  right: 24px;
  width: 36px;
  height: 36px;
  border-radius: 50%;
  background: #1e293b;
  border: 1px solid #2d3149;
  color: #94a3b8;
  font-size: 16px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 2px 8px rgba(0,0,0,0.3);
  z-index: 10;
  transition: all .15s;
}
.scroll-bottom-btn:hover {
  background: #263044;
  color: #cbd5e1;
}

/* ── 气泡操作栏 ── */
.msg-actions {
  display: flex;
  gap: 4px;
  margin-top: 2px;
  opacity: 0;
  transition: opacity 0.15s;
}
.msg-actions.assistant {
  align-self: flex-start;
  margin-left: 4px;
}
.msg-actions.user {
  align-self: flex-end;
  margin-right: 4px;
  flex-direction: row-reverse;
}
.message:hover + .msg-actions,
.msg-actions:hover {
  opacity: 1;
}
.action-btn {
  background: none;
  border: 1px solid transparent;
  color: #475569;
  font-size: 13px;
  cursor: pointer;
  padding: 2px 6px;
  border-radius: 4px;
  line-height: 1;
  transition: all 0.15s;
}
.action-btn:hover {
  color: #94a3b8;
  border-color: #2d3149;
  background: #1e293b;
}

/* ── 复制浮动提示 ── */
:global(.copy-flash) {
  position: fixed;
  top: 36px;
  left: 50%;
  transform: translateX(-50%);
  background: #22c55e22;
  color: #86efac;
  border: 1px solid #22c55e44;
  font-size: 11px;
  padding: 4px 16px;
  border-radius: 6px;
  pointer-events: none;
  z-index: 9999;
  animation: copyFade 1.2s ease forwards;
}
@keyframes copyFade {
  0% { opacity: 1; transform: translateX(-50%) translateY(0); }
  100% { opacity: 0; transform: translateX(-50%) translateY(-12px); }
}

/* ── 设置弹窗 ── */
.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}
.modal-panel {
  background: #1a1d27;
  border: 1px solid #2d3149;
  border-radius: 12px;
  width: 500px;
  max-width: 90vw;
  display: flex;
  flex-direction: column;
}
.modal-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px 20px;
  border-bottom: 1px solid #2d3149;
}
.modal-title {
  font-size: 14px;
  font-weight: 600;
  color: #e2e8f0;
}
.modal-close {
  background: none;
  border: none;
  color: #64748b;
  font-size: 16px;
  cursor: pointer;
  padding: 4px;
  border-radius: 4px;
}
.modal-close:hover { color: #e2e8f0; background: #2d3149; }
.modal-body {
  padding: 16px 20px;
}
.modal-textarea {
  width: 100%;
  background: #0f1117;
  border: 1px solid #2d3149;
  border-radius: 8px;
  color: #e2e8f0;
  padding: 10px 12px;
  font-size: 13px;
  font-family: inherit;
  resize: vertical;
  outline: none;
  line-height: 1.5;
  min-height: 120px;
}
.modal-textarea:focus { border-color: #7c3aed; }
.modal-footer {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 8px;
  padding: 12px 20px;
  border-top: 1px solid #2d3149;
}
.save-tip {
  font-size: 12px;
  color: #86efac;
  margin-right: auto;
}
.btn-cancel {
  background: #1e293b;
  border: 1px solid #2d3149;
  color: #94a3b8;
  padding: 6px 16px;
  border-radius: 6px;
  font-size: 12px;
  cursor: pointer;
}
.btn-cancel:hover { color: #e2e8f0; }
.btn-save {
  background: #7c3aed;
  border: none;
  color: #fff;
  padding: 6px 16px;
  border-radius: 6px;
  font-size: 12px;
  font-weight: 600;
  cursor: pointer;
}
.btn-save:hover { background: #6d28d9; }
.btn-save:disabled { opacity: 0.5; cursor: not-allowed; }

/* ── 大脑循环状态条 ── */
.brain-bar {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 4px 16px;
  background: #1a1d27;
  border-bottom: 1px solid #2d3149;
  font-size: 11px;
  color: #64748b;
  cursor: pointer;
  user-select: none;
  transition: background .15s;
}
.brain-bar:hover { background: #1e2030; }
.brain-bar.running { border-left: 3px solid #7c3aed; }
.brain-bar-icon { font-size: 12px; }
.brain-bar-activity { flex: 1; color: #a78bfa; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.brain-bar-idle { color: #94a3b8; }
.brain-bar-pending { color: #fbbf24; font-weight: 600; }
.brain-bar-toggle { font-size: 9px; color: #475569; }

/* ── 大脑循环详情面板 ── */
.brain-detail {
  background: #14171f;
  border-bottom: 1px solid #2d3149;
  padding: 10px 16px;
  display: flex;
  flex-direction: column;
  gap: 10px;
  font-size: 12px;
}
.bd-title { font-size: 10px; color: #64748b; margin-bottom: 6px; font-weight: 600; }

/* 驱动力 */
.bd-drives { display: flex; flex-direction: column; gap: 4px; }
.bd-drive { display: flex; align-items: center; gap: 8px; }
.bd-drive-label { min-width: 32px; color: #94a3b8; font-size: 11px; }
.bd-drive-bar { flex: 1; height: 6px; background: #2d3149; border-radius: 3px; overflow: hidden; }
.bd-drive-fill { height: 100%; background: linear-gradient(90deg, #7c3aed, #a78bfa); border-radius: 3px; transition: width .3s; }
.bd-drive-val { min-width: 28px; text-align: right; color: #a78bfa; font-size: 11px; }

/* 关注 */
.bd-concerns { display: flex; flex-wrap: wrap; gap: 4px; }
.bd-concern { background: #1e2030; color: #cbd5e1; padding: 2px 8px; border-radius: 4px; font-size: 11px; border: 1px solid #2d3149; }

/* 元信息 */
.bd-meta { display: flex; gap: 16px; color: #94a3b8; font-size: 11px; }
.bd-meta-item { display: flex; align-items: center; gap: 4px; }

/* 反思 */
.bd-reflection { display: flex; flex-direction: column; gap: 4px; }
.bd-rf-row { display: flex; gap: 6px; font-size: 11px; }
.bd-rf-label { color: #64748b; min-width: 28px; flex-shrink: 0; }
.bd-rf-text { color: #cbd5e1; }
.bd-rf-row.dim .bd-rf-text { color: #64748b; }
</style>

// web-react/src/views/ChatView.tsx
import { useEffect, useRef, useState, useCallback } from 'react'
import { useToast } from '../lib/useToast'
import './ChatView.css'

interface ChatMessage {
  id?: number
  role: 'user' | 'assistant' | 'system' | 'tool'
  content: string
  is_thought?: number
  isStreaming?: boolean
  created_at?: string
}

const API_BASE = window.location.origin

interface BrainState {
  life_loop_status: string
  current_activity: string
  current_focus: string
  idle_seconds: number
  energy: number
  mood: { label?: string; valence?: number; arousal?: number }
  open_loop_count: number
  pending_expression_count: number
  scheduler_running: boolean
  drives: Record<string, number>
  top_concerns: Array<{ node_id: string; effective: number }>
  reflection: {
    last_reflection_at: string | null
    last_reflection_summary: string
    beliefs: string[]
    interests: string[]
    goals: string[]
    open_questions: string[]
  }
  last_error: string
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function renderContent(msg: { role: string; content: string }): string {
  if (msg.role === 'user') return escapeHtml(msg.content)
  let html = escapeHtml(msg.content)
  html = html.replace(/```(\w*)\n([\s\S]*?)```/g, '<pre><code class="lang-$1">$2</code></pre>')
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>')
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>')
  html = html.replace(/\n/g, '<br>')
  return html
}

function getDateSeparator(currentTime: string, prevTime: string | null): string {
  if (!currentTime) return ''
  const curDate = currentTime.slice(0, 10)
  if (!prevTime) return curDate
  return curDate !== prevTime.slice(0, 10) ? curDate : ''
}

function formatMsgTime(time: string): string {
  const m = time?.match(/\d{2}:\d{2}:\d{2}/)
  return m ? m[0] : ''
}

function timeAgo(ts: number | null): string {
  if (!ts) return ''
  const diff = Math.floor(Date.now() / 1000 - ts)
  if (diff < 60) return `${diff}秒前`
  if (diff < 3600) return `${Math.floor(diff / 60)}分钟前`
  return `${Math.floor(diff / 3600)}小时前`
}

function fmtIdle(seconds: number): string {
  if (seconds < 60) return `${seconds}s`
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m`
  const h = Math.floor(seconds / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  return `${h}h${m ? ` ${m}m` : ''}`
}

function formatDriveLabel(key: string): string {
  const map: Record<string, string> = { curiosity: '好奇', companionship: '陪伴', self_expression: '表达', completion: '完成' }
  return map[key] || key
}

export default function ChatView() {
  const [messages, setMessages] = useState<ChatMessage[]>([])
  const [sending, setSending] = useState(false)
  const [currentStatus, setCurrentStatus] = useState('')
  const [inputText, setInputText] = useState('')
  const [loopState, setLoopState] = useState<any>({})
  const [showBrainDetail, setShowBrainDetail] = useState(false)
  const [showSettings, setShowSettings] = useState(false)
  const [systemPersona, setSystemPersona] = useState('')
  const [savingPersona, setSavingPersona] = useState(false)
  const [savedTip, setSavedTip] = useState(false)
  const [quotePreview, setQuotePreview] = useState('')
  const [quoteIndex, setQuoteIndex] = useState(-1)
  const [showScrollBtn, setShowScrollBtn] = useState(false)
  const [proactiveLoading, setProactiveLoading] = useState(false)

  const messagesRef = useRef<ChatMessage[]>([])
  const messagesEl = useRef<HTMLDivElement | null>(null)
  const lastSeqRef = useRef(0)
  const evtSourceRef = useRef<EventSource | null>(null)
  const typewriterTimerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const pendingReloadRef = useRef(false)
  const pollTimerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const seqTimerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const toast = useToast()

  messagesRef.current = messages

  const scrollToBottom = useCallback(() => {
    requestAnimationFrame(() => {
      if (messagesEl.current) {
        messagesEl.current.scrollTop = messagesEl.current.scrollHeight
      }
    })
  }, [])

  /* 打字机效果 */
  function typewriter(index: number, full: string) {
    if (!full) return
    setMessages((prev) => {
      const next = [...prev]
      if (next[index]) {
        next[index] = { ...next[index], content: '', isStreaming: true }
      }
      return next
    })
    const step = Math.max(1, Math.ceil(full.length / 50))
    let i = 0
    if (typewriterTimerRef.current) clearInterval(typewriterTimerRef.current)
    typewriterTimerRef.current = setInterval(() => {
      i += step
      const done = i >= full.length
      setMessages((prev) => {
        const next = [...prev]
        if (next[index]) {
          next[index] = { ...next[index], content: done ? full : full.slice(0, i), isStreaming: !done }
        }
        return next
      })
      if (done) {
        if (typewriterTimerRef.current) { clearInterval(typewriterTimerRef.current); typewriterTimerRef.current = null }
        if (pendingReloadRef.current) {
          pendingReloadRef.current = false
          loadMessagesSilent()
        }
      }
    }, 30)
  }

  async function loadMessages() {
    try {
      const resp = await fetch(`${API_BASE}/chat/history`)
      const data = await resp.json()
      if (data.messages) {
        setMessages(data.messages.map((m: any) => ({ role: m.role, content: m.content, created_at: m.created_at, isStreaming: false })))
        scrollToBottom()
      }
      try {
        const seqData = await (await fetch(`${API_BASE}/chat/seq`)).json()
        lastSeqRef.current = seqData.seq || 0
      } catch { /* ignore */ }
    } catch (e) {
      console.error('[chat] load messages failed:', e)
    }
  }

  async function loadMessagesSilent() {
    try {
      const resp = await fetch(`${API_BASE}/chat/history`)
      const data = await resp.json()
      if (!data.messages) return
      const cur = messagesRef.current
      const last = data.messages[data.messages.length - 1]
      const myLast = cur[cur.length - 1]
      if (data.messages.length === cur.length && last?.content === myLast?.content) return
      const prevLastAssistant = [...cur].reverse().find((m) => m.role === 'assistant')?.content
      const prevLen = cur.length
      setMessages(data.messages.map((m: any) => ({ role: m.role, content: m.content, created_at: m.created_at, isStreaming: false })))
      const newLen = data.messages.length
      const newLastAssistantIdx = newLen - 1
      const newLast = data.messages[newLastAssistantIdx]
      if (newLast?.role === 'assistant' && newLast.content && newLast.content !== prevLastAssistant) {
        typewriter(newLastAssistantIdx, newLast.content)
      } else if (newLen !== prevLen) {
        scrollToBottom()
      }
    } catch { /* 静默 */ }
  }

  async function loadState() {
    try {
      const resp = await fetch(`${API_BASE}/chat/state`)
      const data = await resp.json()
      setLoopState(data)
      if (data.current_status) setCurrentStatus(data.current_status)
    } catch { /* ignore */ }
  }

  async function checkSeq() {
    try {
      const data = await (await fetch(`${API_BASE}/chat/seq`)).json()
      if (data.seq > lastSeqRef.current) {
        lastSeqRef.current = data.seq
        reloadIfIdle()
      }
    } catch { /* 静默 */ }
  }

  async function reloadIfIdle() {
    const cur = messagesRef.current
    if (cur.length > 0 && cur[cur.length - 1].isStreaming) {
      pendingReloadRef.current = true
      return
    }
    await loadMessagesSilent()
  }

  function startEventStream() {
    if (evtSourceRef.current || typeof EventSource === 'undefined') return
    const es = new EventSource(`${API_BASE}/brain/events/stream`)
    es.addEventListener('brain_event', (ev: any) => {
      try {
        const payload = JSON.parse(ev.data)
        if (payload.source === 'workmemory' && payload.type === 'new_message') {
          reloadIfIdle()
        }
      } catch { /* 静默 */ }
    })
    es.onerror = () => { /* EventSource 自动重连 */ }
    evtSourceRef.current = es
  }

  function stopEventStream() {
    if (evtSourceRef.current) { evtSourceRef.current.close(); evtSourceRef.current = null }
  }

  useEffect(() => {
    loadMessages()
    loadState()
    pollTimerRef.current = setInterval(loadState, 10000)
    seqTimerRef.current = setInterval(checkSeq, 3000)
    checkSeq()
    startEventStream()
    async function loadWeworkStatus() {
      try { const r = await fetch('/gate/status'); await r.json() } catch { /* ignore */ }
    }
    loadWeworkStatus()
    return () => {
      if (pollTimerRef.current) clearInterval(pollTimerRef.current)
      if (seqTimerRef.current) clearInterval(seqTimerRef.current)
      if (typewriterTimerRef.current) clearInterval(typewriterTimerRef.current)
      stopEventStream()
    }
  }, [])

  async function sendMessage(text: string) {
    if (!text.trim() || sending) return
    const ts = new Date()
    const tsStr = `${ts.getFullYear()}-${String(ts.getMonth() + 1).padStart(2, '0')}-${String(ts.getDate()).padStart(2, '0')} ${String(ts.getHours()).padStart(2, '0')}:${String(ts.getMinutes()).padStart(2, '0')}:${String(ts.getSeconds()).padStart(2, '0')}`
    setMessages((prev) => [...prev, { role: 'user', content: text, created_at: tsStr }])
    scrollToBottom()
    setSending(true)
    try {
      const resp = await fetch(`${API_BASE}/chat/send`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: text }),
      })
      if (resp.status === 503) {
        const data = await resp.json()
        toast.show(data.message || '请先配置 Chat', 'error')
        return
      }
      if (!resp.ok) {
        toast.show(`请求失败 ${resp.status}`, 'error')
        return
      }
    } catch (e: any) {
      toast.show(String(e), 'error')
    } finally {
      setSending(false)
    }
  }

  function handleSend() {
    let text = inputText.trim()
    if (!text || sending) return
    if (quotePreview) {
      text = `> ${quotePreview}\n\n${text}`
      setQuotePreview('')
      setQuoteIndex(-1)
    }
    setInputText('')
    sendMessage(text)
  }

  function handleKeydown(e: React.KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSend()
    }
  }

  async function handleClear() {
    try {
      await fetch(`${API_BASE}/chat/clear`, { method: 'POST' })
      setMessages([])
      toast.show('对话已清空', 'info')
    } catch {
      toast.show('清空失败', 'error')
    }
  }

  async function handleProactive() {
    if (proactiveLoading) return
    setProactiveLoading(true)
    try {
      await fetch(`${API_BASE}/chat/proactive`, { method: 'POST' })
      await loadMessagesSilent()
    } catch { /* ignore */ }
    setProactiveLoading(false)
  }

  async function openSettings() {
    setShowSettings(true)
    setSavedTip(false)
    try {
      const resp = await fetch('/settings/chat')
      const json = await resp.json()
      setSystemPersona(json.data?.system_persona || '')
    } catch { setSystemPersona('') }
  }

  async function saveSettings() {
    setSavingPersona(true)
    try {
      await fetch('/settings/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ system_persona: systemPersona }),
      })
      setSavedTip(true)
      setTimeout(() => setSavedTip(false), 2000)
    } catch { /* ignore */ }
    setSavingPersona(false)
  }

  function quoteMsg(text: string, index: number) {
    const lines = text.split('\n').filter(Boolean)
    let quote = lines.slice(0, 3).join('\n')
    if (lines.length > 3) quote += '\n...'
    setQuotePreview(quote)
    setQuoteIndex(index)
    setTimeout(() => {
      const ta = document.querySelector('.chat-input') as HTMLTextAreaElement
      ta?.focus()
    }, 50)
  }

  function jumpToQuote() {
    if (quoteIndex < 0 || !messagesEl.current) return
    const msgs = messagesEl.current.querySelectorAll('.message')
    const target = msgs[quoteIndex] as HTMLElement
    if (target) {
      target.scrollIntoView({ behavior: 'smooth', block: 'center' })
      target.style.transition = 'background 0.5s'
      target.style.background = 'rgba(124, 58, 237, 0.15)'
      setTimeout(() => { target.style.background = '' }, 1500)
    }
    setQuotePreview('')
    setQuoteIndex(-1)
  }

  async function copyMsgContent(text: string) {
    try { await navigator.clipboard.writeText(text) } catch {
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.position = 'fixed'
      ta.style.opacity = '0'
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
    }
    const flash = document.createElement('div')
    flash.className = 'copy-flash'
    flash.textContent = '已复制'
    document.body.appendChild(flash)
    setTimeout(() => flash.remove(), 1200)
  }

  function onScroll() {
    const el = messagesEl.current
    if (!el) return
    setShowScrollBtn(el.scrollHeight - el.scrollTop - el.clientHeight > 100)
  }

  const brain = loopState.brain
  const stateLabel = (() => {
    if (loopState.is_busy) return { icon: '🟡', text: '思考中...', cls: 'busy' }
    if (loopState.idle_enabled) return { icon: '🟢', text: `已思考 ${loopState.idle_count} 次`, cls: 'idle' }
    return { icon: '⚪', text: '意识流已暂停', cls: 'paused' }
  })()

  const maxTokens = loopState.max_context_tokens || 400000
  const usedTokens = loopState.prompt_tokens || 0
  const tokenPercent = Math.min((usedTokens / maxTokens) * 100, 100)
  const hue = Math.round(120 - (tokenPercent / 100) * 120)
  const tokenColor = `hsl(${hue}, 80%, 45%)`

  return (
    <div className="chat-wrap">
      {/* 顶部状态条 */}
      <div className={`status-bar ${stateLabel.cls}`}>
        <span className="status-icon">{stateLabel.icon}</span>
        <span className="status-text">{stateLabel.text}</span>
        {loopState.idle_enabled && loopState.last_thought_at && (
          <span className="status-detail">上次 {timeAgo(loopState.last_thought_at)}</span>
        )}
        <button className="status-btn" onClick={openSettings} title="系统提示词">⚙</button>
        <button className="status-btn" onClick={handleClear} title="清空对话">🗑</button>
      </div>

      {/* 大脑循环状态条 */}
      {brain && (
        <div className={`brain-bar${brain.scheduler_running ? ' running' : ''}`} onClick={() => setShowBrainDetail((v) => !v)}>
          <span className="brain-bar-icon">{brain.scheduler_running ? '🧠' : '💤'}</span>
          <span className="brain-bar-activity">{brain.current_activity || 'wait'}{brain.current_focus ? ': ' + brain.current_focus.slice(0, 20) : ''}</span>
          <span className="brain-bar-idle">{fmtIdle(brain.idle_seconds || 0)}</span>
          {brain.pending_expression_count > 0 && <span className="brain-bar-pending">{brain.pending_expression_count} 待表达</span>}
          <span className="brain-bar-toggle">{showBrainDetail ? '▲' : '▼'}</span>
        </div>
      )}

      {/* 大脑详情面板 */}
      {showBrainDetail && brain && (
        <div className="brain-detail">
          <div className="bd-section">
            <div className="bd-title">🧬 驱动力</div>
            <div className="bd-drives">
              {Object.entries(brain.drives || {}).map(([key, val]: any) => (
                <div key={key} className="bd-drive">
                  <span className="bd-drive-label">{formatDriveLabel(key)}</span>
                  <div className="bd-drive-bar"><div className="bd-drive-fill" style={{ width: `${val * 100}%` }} /></div>
                  <span className="bd-drive-val">{(val * 100).toFixed(0)}%</span>
                </div>
              ))}
            </div>
          </div>
          {brain.top_concerns?.length > 0 && (
            <div className="bd-section">
              <div className="bd-title">🎯 当前关注</div>
              <div className="bd-concerns">
                {brain.top_concerns.map((c: any) => (
                  <span key={c.node_id} className="bd-concern" title={`effective: ${c.effective}`}>{c.node_id}</span>
                ))}
              </div>
            </div>
          )}
          <div className="bd-section bd-meta">
            <span className="bd-meta-item">能量 {(brain.energy * 100).toFixed(0)}%</span>
            <span className="bd-meta-item">心情 {brain.mood?.label || brain.mood?.valence?.toFixed(2) || '--'}</span>
            <span className="bd-meta-item">{brain.open_loop_count || 0} 闭环</span>
          </div>
          {(brain.reflection?.beliefs?.length > 0 || brain.reflection?.interests?.length > 0) && (
            <div className="bd-section">
              <div className="bd-title">💭 反思</div>
              <div className="bd-reflection">
                {brain.reflection.beliefs?.length > 0 && (
                  <div className="bd-rf-row"><span className="bd-rf-label">信念</span><span className="bd-rf-text">{brain.reflection.beliefs.join('; ')}</span></div>
                )}
                {brain.reflection.interests?.length > 0 && (
                  <div className="bd-rf-row"><span className="bd-rf-label">兴趣</span><span className="bd-rf-text">{brain.reflection.interests.join('; ')}</span></div>
                )}
                {brain.reflection.last_reflection_at && (
                  <div className="bd-rf-row dim"><span className="bd-rf-label">反思于</span><span className="bd-rf-text">{brain.reflection.last_reflection_at.slice(0, 19)}</span></div>
                )}
              </div>
            </div>
          )}
        </div>
      )}

      {/* 消息列表 */}
      <div className="messages" ref={messagesEl} onScroll={onScroll}>
        {messages.length === 0 && (
          <div className="empty-hint">
            <div className="empty-icon">💭</div>
            <div>开始与 AiBrain 对话</div>
            <div className="empty-sub">AI 会自动检索记忆库来理解上下文</div>
          </div>
        )}
        {messages.map((msg, i) => {
          const sep = getDateSeparator(msg.created_at || '', messages[i - 1]?.created_at || null)
          return (
            <div key={i}>
              {sep && <div className="date-separator">{sep}</div>}
              <div className={`message ${msg.role}${msg.is_thought === 1 ? ' thought' : ''}`}>
                {msg.is_thought === 1 && <span className="thought-badge">💭 思绪</span>}
                <div className="msg-content" dangerouslySetInnerHTML={{ __html: renderContent(msg) }} />
                {msg.isStreaming && (
                  <div className="stream-status">
                    <span className="stream-label">{currentStatus}</span>
                    <span className="cursor">▌</span>
                  </div>
                )}
                {msg.created_at && (
                  <div className={`msg-footer ${msg.role}`}>
                    <span className="msg-time">{formatMsgTime(msg.created_at)}</span>
                  </div>
                )}
              </div>
              {!msg.isStreaming && (
                <div className={`msg-actions ${msg.role}`}>
                  <button className="action-btn" onClick={() => copyMsgContent(msg.content)} title="复制">📋</button>
                  <button className="action-btn" onClick={() => quoteMsg(msg.content, i)} title="引用">💬</button>
                </div>
              )}
            </div>
          )
        })}
        {showScrollBtn && <button className="scroll-bottom-btn" onClick={scrollToBottom}>⬇</button>}
      </div>

      {/* 引用预览 */}
      {quotePreview && (
        <div className="quote-preview">
          <div className="quote-preview-bar" />
          <div className="quote-preview-text">{quotePreview}</div>
          <button className="quote-preview-close" onClick={jumpToQuote} title="跳转">↪</button>
          <button className="quote-preview-close" onClick={() => { setQuotePreview(''); setQuoteIndex(-1) }}>✕</button>
        </div>
      )}

      {/* 输入区 */}
      <div className="input-area">
        <textarea
          value={inputText}
          onChange={(e) => setInputText(e.target.value)}
          className="chat-input"
          placeholder="输入消息... (Enter 发送, Shift+Enter 换行)"
          rows={1}
          onKeyDown={handleKeydown}
          disabled={sending}
        />
        <button className="send-btn" onClick={handleSend} disabled={sending || !inputText.trim()} title="发送">➤</button>
        <button className="proactive-btn" onClick={handleProactive} disabled={proactiveLoading} title="猫猫主动说一句">💬</button>
      </div>

      {/* Token 用量 */}
      <div className="token-bar">
        <div className="token-bar-track">
          <div className="token-bar-fill" style={{ width: `${tokenPercent}%`, background: tokenColor }} />
        </div>
        <span className="token-label">
          {(usedTokens / 1000).toFixed(1)}k / {(maxTokens / 1000).toFixed(1)}k ({tokenPercent.toFixed(1)}%)
        </span>
      </div>

      {/* 系统提示词设置弹窗 */}
      {showSettings && (
        <div className="modal-overlay" onClick={(e) => { if (e.target === e.currentTarget) setShowSettings(false) }}>
          <div className="modal-panel">
            <div className="modal-header">
              <div className="modal-title">系统提示词</div>
              <button className="modal-close" onClick={() => setShowSettings(false)}>✕</button>
            </div>
            <div className="modal-body">
              <textarea
                value={systemPersona}
                onChange={(e) => setSystemPersona(e.target.value)}
                className="modal-textarea"
                placeholder="输入系统提示词..."
                rows={8}
              />
            </div>
            <div className="modal-footer">
              {savedTip && <span className="save-tip">✓ 已保存</span>}
              <button className="btn-cancel" onClick={() => setShowSettings(false)}>取消</button>
              <button className="btn-save" onClick={saveSettings} disabled={savingPersona}>
                {savingPersona ? '保存中...' : '保存'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
