// web-react/src/components/StatusBar.tsx
import { useEffect, useState } from 'react'
import { fetchJson } from '../lib/api'
import './StatusBar.css'

interface StatusData {
  model_loaded?: boolean
  qdrant_ready?: boolean
  device?: string
}

export function StatusBar() {
  const [modelLoaded, setModelLoaded] = useState(false)
  const [qdrantReady, setQdrantReady] = useState(false)
  const [device, setDevice] = useState('cpu')
  const [building, setBuilding] = useState(false)
  const [buildMsg, setBuildMsg] = useState('')
  const [buildFailed, setBuildFailed] = useState(false)
  const [buildId, setBuildId] = useState('')
  const [pollTimer, setPollTimer] = useState<ReturnType<typeof setTimeout> | null>(null)

  async function fetchStatus() {
    try {
      const d = await fetchJson<StatusData>('/statusbar/api')
      setModelLoaded(!!d.model_loaded)
      setQdrantReady(!!d.qdrant_ready)
      setDevice(d.device ?? 'cpu')
    } catch {
      /* 保持上次状态 */
    }
  }

  useEffect(() => {
    fetchStatus()
    const timer = setInterval(fetchStatus, 3000)
    return () => clearInterval(timer)
  }, [])

  useEffect(() => () => { if (pollTimer) clearTimeout(pollTimer) }, [pollTimer])

  async function pollBuildStatus(id: string) {
    if (!id) return
    try {
      const res = await fetch(`/overview/frontend/build/status?build_id=${id}`)
      const data = await res.json()
      if (data.status === 'done') {
        setBuildMsg('构建成功')
        setBuildFailed(false)
        setBuilding(false)
        setTimeout(() => {
          setBuildMsg('')
          setTimeout(() => window.location.reload(), 300)
        }, 2000)
      } else if (data.status === 'failed') {
        setBuildMsg('构建失败')
        setBuildFailed(true)
        setBuilding(false)
      } else {
        setPollTimer(setTimeout(() => pollBuildStatus(id), 500))
      }
    } catch {
      setBuildMsg('构建失败')
      setBuildFailed(true)
      setBuilding(false)
    }
  }

  async function triggerBuild() {
    if (building) return
    setBuilding(true)
    setBuildMsg('构建中...')
    setBuildFailed(false)
    setBuildId('')
    try {
      const res = await fetch('/overview/frontend/build', { method: 'POST' })
      const data = await res.json()
      if (data.build_id) {
        setBuildId(data.build_id)
        pollBuildStatus(data.build_id)
      } else {
        setBuildMsg('构建失败')
        setBuildFailed(true)
        setBuilding(false)
      }
    } catch {
      setBuildMsg('构建失败')
      setBuildFailed(true)
      setBuilding(false)
    }
  }

  return (
    <div className="statusbar">
      <div className="statusbar-item">
        <span>{modelLoaded ? '模型就绪' : '模型加载中'}</span>
        <div className={`statusbar-dot ${modelLoaded ? 'ok' : 'loading'}`} />
      </div>
      <div className="statusbar-item">
        <span>Qdrant</span>
        <div className={`statusbar-dot ${qdrantReady ? 'ok' : 'err'}`} />
      </div>
      <div className="statusbar-item">
        <span>{device === 'cuda' ? 'GPU' : 'CPU'}</span>
      </div>
      <div className="statusbar-right">
        {buildMsg ? (
          <span className={`build-msg ${buildFailed ? 'fail' : ''} ${building ? 'building' : ''}`}>{buildMsg}</span>
        ) : (
          <button className="build-btn" onClick={triggerBuild} title="构建前端">构建</button>
        )}
      </div>
    </div>
  )
}

// web/src/components/StatusBar.vue
<script setup lang="ts">
import { useStatusStore } from '@/stores/status'
import { usePolling } from '@/composables/usePolling'
import { ref } from 'vue'

const statusStore = useStatusStore()
const building = ref(false)
const buildMsg = ref('')
const buildFailed = ref(false)
const buildId = ref('')
let pollTimer: ReturnType<typeof setTimeout> | null = null

const { start } = usePolling(() => statusStore.fetchStatus(), 3000)

statusStore.fetchStatus()
start()

async function pollBuildStatus(id: string) {
  if (!id) return
  try {
    const res = await fetch(`/overview/frontend/build/status?build_id=${id}`)
    const data = await res.json()
    if (data.status === 'done') {
      buildMsg.value = '构建成功'
      buildFailed.value = false
      building.value = false
      clearTimeout(pollTimer)
      setTimeout(() => {
        buildMsg.value = ''
        setTimeout(() => window.location.reload(), 300)
      }, 2000)
    } else if (data.status === 'failed') {
      buildMsg.value = '构建失败'
      buildFailed.value = true
      building.value = false
      clearTimeout(pollTimer)
      setTimeout(() => { buildMsg.value = '' }, 2000)
    } else {
      // 继续轮询
      pollTimer = setTimeout(() => pollBuildStatus(id), 500)
    }
  } catch (e) {
    buildMsg.value = '构建失败'
    buildFailed.value = true
    building.value = false
    clearTimeout(pollTimer)
  }
}

async function triggerBuild() {
  if (building.value) return
  building.value = true
  buildMsg.value = '构建中...'
  buildFailed.value = false
  buildId.value = ''
  try {
    const res = await fetch('/overview/frontend/build', { method: 'POST' })
    const data = await res.json()
    if (data.build_id) {
      buildId.value = data.build_id
      pollBuildStatus(data.build_id)
    } else {
      buildMsg.value = '构建失败'
      buildFailed.value = true
      building.value = false
    }
  } catch (e) {
    buildMsg.value = '构建失败'
    buildFailed.value = true
    building.value = false
  }
}
</script>

<template>
  <div class="statusbar">
    <div class="statusbar-item">
      <span>{{ statusStore.modelLoaded ? '模型就绪' : '模型加载中' }}</span>
      <div
        class="statusbar-dot"
        :class="{
          ok: statusStore.modelLoaded,
          loading: !statusStore.modelLoaded,
        }"
      />
    </div>
    <div class="statusbar-item">
      <span>Qdrant</span>
      <div
        class="statusbar-dot"
        :class="{
          ok: statusStore.qdrantReady,
          err: !statusStore.qdrantReady,
        }"
      />
    </div>
    <div class="statusbar-item">
      <span>{{ statusStore.device === 'cuda' ? 'GPU' : 'CPU' }}</span>
    </div>
    <div class="statusbar-right">
      <span v-if="buildMsg" class="build-msg" :class="{ fail: buildFailed, building: building }">{{ buildMsg }}</span>
      <button v-else class="build-btn" @click="triggerBuild" title="构建前端">构建</button>
    </div>
  </div>
</template>

<style scoped>
.statusbar {
  height: 28px; background: #1a1d27; border-top: 1px solid #2d3149;
  display: flex; align-items: center; justify-content: flex-end;
  gap: 16px; padding: 0 16px; font-size: 11px; color: #64748b;
  flex-shrink: 0;
}
.statusbar-item { display: flex; align-items: center; gap: 5px; }
.statusbar-dot {
  width: 6px; height: 6px; border-radius: 50%; flex-shrink: 0;
  box-sizing: content-box; transform: none;
}
.statusbar-dot.ok {
  background: #22c55e; box-shadow: 0 0 5px #22c55e;
  animation: dot-pulse-ok 2s ease-in-out infinite;
}
.statusbar-dot.err {
  background: #ef4444; box-shadow: 0 0 4px #ef4444;
}
.statusbar-dot.loading {
  background: #eab308; box-shadow: 0 0 5px #eab308;
  animation: dot-pulse-loading 1s ease-in-out infinite;
}
@keyframes dot-pulse-ok {
  0%, 100% { opacity: 1; box-shadow: 0 0 5px #22c55e; }
  50% { opacity: 0.5; box-shadow: 0 0 2px #22c55e; }
}
@keyframes dot-pulse-loading {
  0%, 100% { opacity: 1; box-shadow: 0 0 5px #eab308; }
  50% { opacity: 0.5; box-shadow: 0 0 2px #eab308; }
}
.statusbar-right { display: flex; align-items: center; gap: 8px; margin-left: 8px; }
.build-btn {
  padding: 2px 10px; background: #7c3aed22; border: 1px solid #7c3aed44;
  border-radius: 4px; font-size: 10px; color: #a78bfa; cursor: pointer;
  transition: all .2s;
}
.build-btn:hover { background: #7c3aed44; color: #c4b5fd; }
.build-msg { font-size: 10px; color: #86efac; }
.build-msg.fail { color: #ef4444; }
.build-msg.building { color: #eab308; animation: build-pulse 2.5s ease-in-out infinite; }
@keyframes build-pulse {
  0%, 100% { opacity: 1; text-shadow: 0 0 4px #eab30888; }
  50% { opacity: 0.6; text-shadow: none; }
}
</style>
